name: chatting_app_1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.10
  fluttertoast: ^8.2.5
  image_picker: ^1.1.1
  path_provider: ^2.1.3
  velocity_x: ^4.2.0
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
  - lib/images/

  fonts:
      - family: Poppins
        fonts:
          - asset: lib/fonts/Poppins-Regular.ttf
          - asset: lib/fonts/Poppins-Thin.ttf
          - asset: lib/fonts/Poppins-Light.ttf
